name: .NET Core Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Publish with dotnet
      run: dotnet publish --o publish

    - name: Action Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        # File to upload to the release
        file: publish\MentorSpeedDatingApp.exe
