name: .NET Core Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Publish with dotnet
      run: dotnet publish -r win-x64 -c Release --self-contained true /p:useapphost=true

    - name: Action Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        # File to upload to the release
        file: bin\Release\netcoreapp3.1\win-x64\MentorSpeedDatingApp.exe
